### ISSUE TITLE
Could not add Multiple skills

### ISSUE THREAD

**Issue by AadharshAadhithya** [samrobbins85/hugo-developer-portfolio#10]
Hi sam!That was an amazing theme, thanks for the theme. 

When I try to add multiple skill items in homepage.yml , 

```
skill:
  enable: true

  item:
    - title: Python
      logo: https://res.cloudinary.com/dbwuq1kps/image/upload/v1615733646/personalwebsite/5848152fcef1014c0b5e4967_glhwi8.png
      description: Details coming soon, contact me if you want to know more

  item:
    - title: cpp
      logo: https://res.cloudinary.com/dbwuq1kps/image/upload/v1615734208/personalwebsite/c-logo-icon-28389_v1dvpq.png
      description: Details coming soon, contact me if you want to know more

```
the bottom most one tend to be appearing (this case , cpp tends to ovewrite the python item) .  is there any fix?
