### ISSUE TITLE
Skill section in homepage is broken when title includes symbols

### ISSUE THREAD

**Issue by granddaifuku** [samrobbins85/hugo-developer-portfolio#12]
Hi!  When I try to apply this great theme to mine, I came across following problems.

I am trying to show "c++" as my skill.
I wrote my `data/homepage.yml` as follows.
```
skill:
  enable: true
  item:
    - title: c++
      logo: /images/logos/cpp.svg
      description: Details coming soon, contact me if you want to know more
```

And then I run a development server and clicked the logo of c++, there's no modal window and only change is that the logo turned into "c++"  strings.
![Screen Shot 2021-05-03 at 16 03 52](https://user-images.githubusercontent.com/49578068/116849179-30f60c00-ac29-11eb-8af4-a86ce0591140.png)

## What I tested
* change title c++ to "c++" (enclose c++ string with double quotes)
I got the same result as above.

* change title c++ to c# (change to another symbol)
I got the same result as above.

* change title c++ to c3 (add not alphabetical letter instead of adding symbols)
It worked

**Comment by samrobbins85** [comment]
Thanks for the report, I'm a bit busy at the moment, so it won't be fixed for a little while, but I'll try and get this fixed soon

**Comment by samrobbins85** [comment]
Hi! Sorry this took a while, I've just pushed a commit that helps with this https://github.com/samrobbins85/hugo-developer-portfolio/commit/cf3b53a6ebbc8e3e257cdc7828ea2df7bda464ca. Unfortunately, I don't know enough about UIkit internals to allow symbols in the triggers for the modal. My workaround is adding a `titlealt` key, which you can set to something that doesn't contain symbols, for example `CPlusPlus`, this will just be used internally and not displayed to the user, and will allow everything to work as you'd expect.

Here's an example of using it:

```yml
- title: C++
      titlealt: CPlusPlus
      logo: https://res.cloudinary.com/samrobbins/image/upload/v1591793272/logos/logos_javascript_adj1dx.svg
      description: Details coming soon, contact me if you want to know more
```
