### ISSUE TITLE
Cannot get tags to show up in portfolio page

### ISSUE THREAD

**Issue by sebescudie** [samrobbins85/hugo-developer-portfolio#8]
Hello there!

There's something I don't get with the way tags are handled in the portfolio list page. This the content of my `data/portfolio.yml` :

```
portfolio:
  filter:
    - label: plugin
      value: plugin
    - label: commercial
      value: commercial
    - label: installation
      value: installation
    - label: backend
      value: backend
    - label: software
      value: software
    - label: teaching
      value: teaching
    - label: hardware
      value: hardware
```

And in one of my portfolio's article, I set the header as so :

```
categories = ["backend", "hardware"]
```

Though in the portfolio list page, I only get the `All` tag, the others do not show up (I would have expected "backend" and "hardware" buttons).

Have I missed something?

Thanks!

EDIT: looks related to #5

**Comment by samrobbins85** [comment]
Sorry, I should have left an example, or maybe the docs are wrong. The `portfolio.yml` root key should be `filter`, like this

```yml
filter:
  - label: Web Dev
    value: web-dev
```
